### ISSUE TITLE
Add Health Check 

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate-Labs/tg-group-profile-manager#13]
Hi!
I found out that the slack bot doesn't have a health check route.
I expect to get 200 from /healthcheck

**Comment by emrul** [comment]
Hey @ErezWeiss - thanks for opening the issue. A health check would be great, we’d definitely be happy to review a PR if you could submit one for it.

**Comment by ErezWeiss** [comment]
https://github.com/Twingate-Labs/tg-group-profile-manager/pull/14#pullrequestreview-2288595441

**Comment by ErezWeiss** [comment]
@emrul

**Comment by chenbishop** [comment]
@ErezWeiss 

The PR has been tested, merged and released.

Please update the helm chart version and redeploy to reflect the changes.

**Comment by ErezWeiss** [comment]
Thank you!
