### ISSUE TITLE
Error when trying to send request after I already have it

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate-Labs/tg-group-profile-manager#7]
![image](https://github.com/Twingate-Labs/tg-group-profile-manager/assets/35471632/05ef63ba-b761-449a-beaa-f9f18b96bd01)
Hi!
I have one profile. Once I granted access to it and I tried to grant it again - nothing happened and an exception was raised inside the pod.
Please add an interactive message for the endpoint user, and handle the exception inside the code.

**Comment by chenbishop** [comment]
@ErezWeiss Thank you for raising this, I think the issue is caused by the user already has access to all groups in the profile. 

We will look into the option to prompt user a message when this happens.
