### ISSUE TITLE
Feature request | approverGroup to be a set and not only single group

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate-Labs/tg-group-profile-manager#8]
Hi!
We want the approverGroup to be able to have more than one group (FE managers & BE managers for instance)
@emrul Thanks in advance!!

**Comment by emrul** [comment]
Hi @ErezWeiss thanks for getting in touch! What you're asking for will best be managed within your Identity Provider / Directory by creating a group that compromises of the two subgroups you're interested in. Doing it within the Slackbot is outside of our planned scope for this project.
