### ISSUE TITLE
When asking for approval, the timer starts from the request and not from the approval

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate-Labs/tg-group-profile-manager#9]
Hi guys!
When asking for approval, the timer starts from the request, not the approval.
So if I ask for an hour, and get the approval after 59 mins, I'll get only 1 min of access.
Here is a picture:
![image (2)](https://github.com/Twingate-Labs/tg-group-profile-manager/assets/35471632/6dd9c396-b0df-43b6-aa85-09bea499f5a2)

**Comment by chenbishop** [comment]
Hi Erez, thank you for the feedback. Do you think in general it is better to have timer start from approval instead?

**Comment by ErezWeiss** [comment]
Sure.

**Comment by ErezWeiss** [comment]
The approver knows that he's opening a session that will start immediately on approval.

**Comment by chenbishop** [comment]
Thank you! we will put this on our todo list.

**Comment by ErezWeiss** [comment]
@emrul Hi!
any news?
Developers keep asking for it :)

**Comment by chenbishop** [comment]
@ErezWeiss apologies for the wait. The new version of slack bot is now released which changed the selfserveapproval expiration start time from request time to approval time.

If possible could you upgrade your help chart to the latest version 0.1.7 and this should apply the changes directly, let me know how it goes.

<img width="737" alt="image" src="https://github.com/user-attachments/assets/d70a7558-22bd-4017-b619-a8db8daf2103">

**Comment by ErezWeiss** [comment]
Worked, thank you guys
